// auto generated file
// this file has been generated by make in examples directory
logic [7:0] boot_program[256];

assign boot_program = '{
        0: 8'hA9,
        1: 8'h70,
        2: 8'h85,
        3: 8'h04,
        4: 8'hA9,
        5: 8'h00,
        6: 8'h85,
        7: 8'h05,
        8: 8'hA0,
        9: 8'h02,
        10: 8'hB9,
        11: 8'h1A,
        12: 8'h02,
        13: 8'hA9,
        14: 8'h01,
        15: 8'hA0,
        16: 8'h02,
        17: 8'h91,
        18: 8'h04,
        19: 8'hCF,
        20: 8'hDF,
        21: 8'h00,
        22: 8'h00,
        23: 8'hFF,
        24: 8'h3A,
        25: 8'h05,
        26: 8'h01,
        27: 8'h02,
        28: 8'h03,
        29: 8'h04,
        30: 8'h05,
        default: 8'hEA
    };
parameter logic[7:0] boot_program_length = 31;
