// auto generated file
// this file has been generated by make in examples directory
logic [7:0] boot_program[256];

assign boot_program = '{
        '8'hA9,
        '8'h41,
        '8'h8D,
        '8'h00,
        '8'hE0,
        '8'hEF,
        default: 8'hEA
    };
parameter logic[7:0] boot_program_length = 6;
